# Generated by Django 5.1.1 on 2024-09-17 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todos',
            name='finshed',
        ),
        migrations.AddField(
            model_name='todos',
            name='finished',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='todos',
            name='deadline',
            field=models.DateField(),
        ),
    ]
