# Generated by Django 5.1.1 on 2024-09-17 12:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0002_remove_todos_finshed_todos_finished_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Todos',
            new_name='Todo',
        ),
    ]
